/**
 * Reads packages/ui/styles/theme.css — the Tailwind v4, CSS-first source of
 * every colour and radius the web apps use — and emits tailwind.tokens.js for
 * NativeWind 4 / Tailwind 3.4, which cannot read `@theme` blocks.
 *
 * WHY A SCRIPT AND NOT A DEPENDENCY. `@koolee/ui` pulls Next, Radix, GSAP and
 * MapLibre; none of that can load on a phone. Reading the stylesheet by path
 * keeps the driver app on the SAME tokens without the package. Run it
 * whenever theme.css changes (`pnpm --filter @koolee/driver tokens`) and
 * commit the output; a test pins the output to the source.
 *
 * What crosses over: the semantic tokens (`--primary`, `--border`, …) as RGB
 * triplets so `bg-primary/80` works through `rgb(var(--primary) / <alpha>)`,
 * the literal brand scales (navy, sky, tag, cream) as hex, and the three
 * radii. What does not: `--font-*` (faces load through expo-font), the
 * clamp()-based display sizes, CSS shadows, easings and keyframes.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "../../../packages/ui/styles/theme.css");
const OUT = resolve(here, "../tailwind.tokens.js");

export function buildTokens(cssText) {
  const css = cssText.replace(/\/\*[\s\S]*?\*\//g, "");

  function block(head) {
    const start = css.indexOf(head);
    if (start < 0) throw new Error(`theme.css: "${head}" not found`);
    const open = css.indexOf("{", start);
    let depth = 0;
    for (let i = open; i < css.length; i += 1) {
      if (css[i] === "{") depth += 1;
      else if (css[i] === "}") {
        depth -= 1;
        if (depth === 0) return css.slice(open + 1, i);
      }
    }
    throw new Error(`theme.css: unbalanced braces after "${head}"`);
  }

  function decls(body) {
    const out = {};
    for (const m of body.matchAll(/--([\w-]+)\s*:\s*([^;{}]+);/g))
      out[m[1]] = m[2].trim();
    return out;
  }

  const HSL = /^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%\s+(\d+(?:\.\d+)?)%$/;
  function hslToRgbTriplet(v) {
    const m = HSL.exec(v);
    if (!m) return null;
    const h = Number(m[1]);
    const s = Number(m[2]) / 100;
    const l = Number(m[3]) / 100;
    const k = (n) => (n + h / 30) % 12;
    const a = s * Math.min(l, 1 - l);
    const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, 9 - k(n), 1));
    return [f(0), f(8), f(4)].map((x) => Math.round(x * 255)).join(" ");
  }

  const root = decls(block(":root {"));
  const light = {};
  const semantic = {};
  for (const [name, value] of Object.entries(root)) {
    const rgb = hslToRgbTriplet(value);
    if (rgb) {
      light[`--${name}`] = rgb;
      semantic[name] = `rgb(var(--${name}) / <alpha-value>)`;
    }
  }
  const dark = {};
  for (const [name, value] of Object.entries(decls(block(".dark {")))) {
    const rgb = hslToRgbTriplet(value);
    if (rgb) dark[`--${name}`] = rgb;
  }

  const colors = {};
  for (const [name, value] of Object.entries(decls(block("@theme {")))) {
    if (!name.startsWith("color-")) continue;
    if (value === "initial" || value.includes("var(")) continue;
    const [scale, ...rest] = name.slice("color-".length).split("-");
    (colors[scale] ??= {})[rest.join("-") || "DEFAULT"] = value;
  }
  for (const [scale, steps] of Object.entries(colors)) {
    if (Object.keys(steps).length === 1 && steps.DEFAULT) colors[scale] = steps.DEFAULT;
  }

  const radiusRem = parseFloat(root.radius ?? "0.625rem");
  const px = (rem) => `${Math.round(rem * 16)}px`;
  const borderRadius = {
    lg: px(radiusRem),
    md: px(radiusRem - 2 / 16),
    sm: px(radiusRem - 4 / 16),
  };

  return { colors: { ...colors, ...semantic }, vars: { light, dark }, borderRadius };
}

export function renderTokens(tokens) {
  return (
    "/* GENERATED by scripts/theme-tokens.mjs from packages/ui/styles/theme.css. Do not edit. */\n" +
    `module.exports = ${JSON.stringify(tokens, null, 2)};\n`
  );
}

const isMain =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  writeFileSync(OUT, renderTokens(buildTokens(readFileSync(SRC, "utf8"))));
  console.log(`tokens: wrote ${OUT}`);
}
