-- The booking carries its own doorstep.
--
-- Generated by db:generate, then hand-edited for the part a diff cannot see:
-- the five NOT NULL columns are added NULLABLE, BACKFILLED from the address
-- each booking currently points at, and only then constrained. Adding a NOT
-- NULL column with no default to a populated table fails outright, and a
-- DEFAULT '' would have quietly written empty addresses onto real bookings.
--
-- After this, `pickup_address_id` is provenance only: it says which saved
-- address the booking was made from, and goes NULL when the customer deletes
-- it. Every reader takes the address off the booking.
ALTER TABLE "bookings" DROP CONSTRAINT "bookings_pickup_address_id_addresses_id_fk";--> statement-breakpoint
ALTER TABLE "bookings" ALTER COLUMN "pickup_address_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "destination_airport" varchar(3);--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_line1" text;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_line2" text;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_city" text;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_state" varchar(2);--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_zip" varchar(10);--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_lat" double precision;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_lng" double precision;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pickup_place_id" text;--> statement-breakpoint

-- Backfill. Every existing booking has an address by the old NOT NULL
-- constraint, so this leaves no row behind and the SET NOT NULLs below cannot
-- fail. If one ever did, the migration aborts in its own transaction rather
-- than half-applying.
UPDATE "bookings" AS b
SET
  "pickup_line1" = a."line1",
  "pickup_line2" = a."line2",
  "pickup_city" = a."city",
  "pickup_state" = a."state",
  "pickup_zip" = a."zip",
  "pickup_lat" = a."lat",
  "pickup_lng" = a."lng",
  "pickup_place_id" = a."place_id"
FROM "addresses" AS a
WHERE a."id" = b."pickup_address_id";--> statement-breakpoint

ALTER TABLE "bookings" ALTER COLUMN "pickup_line1" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ALTER COLUMN "pickup_city" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ALTER COLUMN "pickup_state" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ALTER COLUMN "pickup_zip" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_pickup_address_id_addresses_id_fk" FOREIGN KEY ("pickup_address_id") REFERENCES "public"."addresses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bookings_pickup_zip_idx" ON "bookings" USING btree ("pickup_zip");
