-- Who opened this shift, when it was not the driver.
--
-- Generated by db:generate; only this comment is hand-added.
--
-- `adminStartShiftOnBehalf` is the pair to `adminForceEndShift`, which has
-- existed since Tier 4 — the console could end somebody's shift and not start
-- one, so a driver whose phone was dead could be taken OFF the road by an
-- admin but not put back on it.
--
-- The actor could not go in `custody_events`: `booking_id` is NOT NULL and a
-- shift belongs to no booking. Force-end gets away with it because it always
-- touches bookings (it releases their pickups); a start touches none.
-- `admin_audit_log` is the general answer and is still deferred
-- (LAUNCH-CHECKLIST P19), so the fact lives on the row it is a fact about.
--
-- ADDITIVE AND NULLABLE. No backfill: every existing shift WAS self-started,
-- which is exactly what NULL means here. No row is rewritten, the lock is the
-- brief ACCESS EXCLUSIVE that any ADD COLUMN takes, and old code that never
-- selects the column is unaffected — so this is expand-safe in both deploy
-- orders, unlike 0033 (§9.5).
--
-- `ON DELETE set null` rather than `restrict`: an admin who leaves must not be
-- undeletable because they once started somebody's shift, and the shift is
-- still a true record of itself without their id.

ALTER TABLE "driver_shifts" ADD COLUMN "started_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "driver_shifts" ADD CONSTRAINT "driver_shifts_started_by_user_id_users_id_fk" FOREIGN KEY ("started_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;