-- Every position a driver's phone reported, kept briefly.
--
-- Generated by db:generate; only this comment is hand-added.
--
-- WHY. `driver_positions` holds ONE row per driver and keeps no history, so
-- the most important operational question about the whole subsystem is
-- unanswerable: a driver says their location kept dropping, and there is no
-- way to tell whether it did, for how long, how often, or on whose phone. The
-- only evidence was a customer noticing a pin had stopped moving. With this
-- table a gap is a hole in a sequence rather than a rumour.
--
-- STILL NOT EVIDENCE. Same distinction `driver_positions` draws against
-- `custody_events`: a browser geolocation ping at street resolution, with no
-- photo, no seal and no actor beside it. Diagnostics, never a dispute.
--
-- TWO TIMESTAMPS. `recorded_at` is the DEVICE's fix time, `created_at` the
-- server's write time. Far apart means a replay out of the offline queue —
-- "this driver was in a tunnel", which needs a different response from ops
-- than "this driver stopped reporting".
--
-- RISK ON APPLY: none worth naming. A CREATE TABLE on a name that does not
-- exist, two foreign keys, two indexes on the table being created. It takes no
-- lock on `users` or `driver_shifts` beyond the brief SHARE ROW EXCLUSIVE that
-- adding a referencing FK requires, scans no existing rows, and is reversible
-- with one DROP TABLE.
--
-- RETENTION IS NOT OPTIONAL. This is the highest-volume write in the system —
-- a row per driver per 20-45s of every shift. The sweep that deletes rows past
-- the retention window is part of the same slice; `recorded_at` is indexed for
-- it. Shipping the table without the sweep is how a disk fills up.

CREATE TABLE "driver_position_pings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"staff_user_id" uuid NOT NULL,
	"driver_shift_id" uuid NOT NULL,
	"lat" double precision NOT NULL,
	"lng" double precision NOT NULL,
	"recorded_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "driver_position_pings_lat_range_check" CHECK ("driver_position_pings"."lat" between -90 and 90),
	CONSTRAINT "driver_position_pings_lng_range_check" CHECK ("driver_position_pings"."lng" between -180 and 180)
);
--> statement-breakpoint
ALTER TABLE "driver_position_pings" ADD CONSTRAINT "driver_position_pings_staff_user_id_users_id_fk" FOREIGN KEY ("staff_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "driver_position_pings" ADD CONSTRAINT "driver_position_pings_driver_shift_id_driver_shifts_id_fk" FOREIGN KEY ("driver_shift_id") REFERENCES "public"."driver_shifts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "driver_position_pings_staff_recorded_idx" ON "driver_position_pings" USING btree ("staff_user_id","recorded_at");--> statement-breakpoint
CREATE INDEX "driver_position_pings_recorded_at_idx" ON "driver_position_pings" USING btree ("recorded_at");