export {
  availableEvents,
  canTransition,
  EVENT_TYPES,
  IllegalTransitionError,
  isTerminal,
  nextStatus,
  TERMINAL_STATUSES,
  TRANSITIONS,
  transition,
  transitionOrThrow,
  type BookingEvent,
  type CustodyEventDraft,
  type TransitionableBooking,
  type TransitionActor,
  type TransitionInput,
  type TransitionResult,
  type TransitionSuccess,
  type TransitionTable,
} from "./state-machine";
